### ISSUE TITLE
ArgumentOutOfRangeException in ParseAsUTF8String

### ISSUE THREAD

**Issue by oddbear** [tlewis17/TouchPortalAPI#7]
Tested both from NuGet and cloned Repo (lastest master commit in picture).

I am not sure why this happens, as I cannot always reproduce it (will update if I figure out more).
When I change values on a valueChoices list in a dynamic action (inlined), some times this happens, and the choice is selected in TouchPortal, but the OnListChangeEventHandler is not called.

![image](https://user-images.githubusercontent.com/2109782/105034990-9ba88080-5a5a-11eb-9931-1be478110aec.png)

Message: `Specified argument was out of the range of valid values. (Parameter 'start')`

```csharp
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.ReadOnlyMemory`1.Slice(Int32 start, Int32 length)
   at System.Buffers.ReadOnlySequence`1.Enumerator.MoveNext()
   at TouchPortalApi.Extensions.ReadOnlySquenceByteExtension.ParseAsUTF8String(ReadOnlySequence`1 slice, Int32 stringLengthEstimate) in C:\Users\oddbj\source\repos\TouchPortalAPI\TouchPortalApi\Extensions\ReadOnlySquenceByteExtension.cs:line 22
   at TouchPortalApi.MessageProcessor.ProcessLine(ReadOnlySequence`1 line) in C:\Users\oddbj\source\repos\TouchPortalAPI\TouchPortalApi\MessageProcessor.cs:line 87
```

**Comment by oddbear** [comment]
Tried changing random stuff until the problem went away.
By changing `ProcessQueueingService` `UnboundedChannelOptions`, the problem seemed to go away. More testing needed (this option might be the wrong fix).
```csharp
var channel = Channel.CreateUnbounded<ReadOnlySequence<byte>>(new UnboundedChannelOptions()
      {
          SingleReader = true,
          AllowSynchronousContinuations = true
      });
```
